/*
 * To change this template comment, edit WF_DATABASE.TEMPLATES.TEMPLATE_TRIGGER1
 */
CREATE OR REPLACE TRIGGER TEMPLATE_TRIGGER1 
BEFORE INSERT OR UPDATE OR DELETE ON TEMPLATE_TABLE1 
BEGIN
  NULL;
END;
/
